### ISSUE TITLE
[GDB] Memory leaks in disassembler

### ISSUE THREAD

**Issue by shahab-vahedi** [foss-for-synopsys-dwc-arc-processors/binutils-gdb#39]
Build:
```
flags="-g -fsanitize=address"
configure ... CFLAGS="${flags}" CXXFLAGS="${flags}"
```

Run any sample debugging session and then terminate GDB:
```
Direct leak of 288 byte(s) in 1 object(s) allocated from:
    #0 0x7f831d13e6be in __interceptor_calloc (/usr/lib/libasan.so.5+0x10c6be)
    #1 0x55d750039226 in init_arc_disasm_info /data/work/repos/gdb-master/opcodes/arc-dis.c:150
    #2 0x55d75003c9a7 in print_insn_arc /data/work/repos/gdb-master/opcodes/arc-dis.c:961
    #3 0x55d74ef2ee25 in default_print_insn(unsigned long, disassemble_info*) /data/work/repos/gdb-master/gdb/arch-utils.c:995
    #4 0x55d74ef1544e in arc_delayed_print_insn(unsigned long, disassemble_info*) /data/work/repos/gdb-master/gdb/arc-tdep.c:1562
    #5 0x55d7500406b5 in arc_insn_decode /data/work/repos/gdb-master/opcodes/arc-dis.c:1464
    #6 0x55d74ef14b32 in arc_analyze_prologue /data/work/repos/gdb-master/gdb/arc-tdep.c:1411
    #7 0x55d74ef15c81 in arc_make_frame_cache /data/work/repos/gdb-master/gdb/arc-tdep.c:1717
    #8 0x55d74ef1601e in arc_frame_this_id /data/work/repos/gdb-master/gdb/arc-tdep.c:1752
    #9 0x55d74f49a433 in compute_frame_id /data/work/repos/gdb-master/gdb/frame.c:550
    #10 0x55d74f49a76e in get_frame_id(frame_info*) /data/work/repos/gdb-master/gdb/frame.c:582
    #11 0x55d74f606d84 in print_stop_location /data/work/repos/gdb-master/gdb/infrun.c:8325
    #12 0x55d74f6070cf in print_stop_event(ui_out*, bool) /data/work/repos/gdb-master/gdb/infrun.c:8377
    #13 0x55d74fe13303 in tui_on_normal_stop /data/work/repos/gdb-master/gdb/tui/tui-interp.c:98
    #14 0x55d74eec4dc2 in std::_Function_handler<void (bpstats*, int), void (*)(bpstats*, int)>::_M_invoke(std::_Any_data const&, bpstats*&&, int&&) /usr/include/c++/9.3/bits/std_function.h:300
    #15 0x55d74f613305 in std::function<void (bpstats*, int)>::operator()(bpstats*, int) const /usr/include/c++/9.3/bits/std_function.h:688
    #16 0x55d74f610b9c in gdb::observers::observable<bpstats*, int>::notify(bpstats*, int) const /data/work/repos/gdb-master/gdb/../gdbsupport/observable.h:106
    #17 0x55d74f6086f6 in normal_stop() /data/work/repos/gdb-master/gdb/infrun.c:8655
    #18 0x55d74f5e9c1c in fetch_inferior_event() /data/work/repos/gdb-master/gdb/infrun.c:4032
    #19 0x55d74f5a400c in inferior_event_handler(inferior_event_type) /data/work/repos/gdb-master/gdb/inf-loop.c:42
    #20 0x55d74fa91f77 in remote_async_serial_handler /data/work/repos/gdb-master/gdb/remote.c:14160
    #21 0x55d74fbb70c8 in run_async_handler_and_reschedule /data/work/repos/gdb-master/gdb/ser-base.c:137
    #22 0x55d74fbb7361 in fd_event /data/work/repos/gdb-master/gdb/ser-base.c:188
    #23 0x55d7510ae0ef in handle_file_event /data/work/repos/gdb-master/gdbsupport/event-loop.cc:548
    #24 0x55d7510ae92c in gdb_wait_for_event /data/work/repos/gdb-master/gdbsupport/event-loop.cc:673
    #25 0x55d7510ac907 in gdb_do_one_event() /data/work/repos/gdb-master/gdbsupport/event-loop.cc:215
    #26 0x55d74f731929 in start_event_loop /data/work/repos/gdb-master/gdb/main.c:356
    #27 0x55d74f731c39 in captured_command_loop /data/work/repos/gdb-master/gdb/main.c:416
    #28 0x55d74f735239 in captured_main /data/work/repos/gdb-master/gdb/main.c:1253
    #29 0x55d74f7352c9 in gdb_main(captured_main_args*) /data/work/repos/gdb-master/gdb/main.c:1268

```

**Comment by claziss** [comment]
Nice one mate, I think we just need to replace the calloc call to xcalloc.
